### ISSUE TITLE
Register existing assets at Broker on connector startup

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-extensions#224]
# Feature Request

## Description
If a conenctor is shut down, assets and the connector itself are unregistered from the broker. If the connector is started up again, the connector is registered again, but not the assets. The assets shall be registered at the broker after startup again.

### Requirements
Please implement registering in a timely scheduled loop to avoid DDOSing Broker if hundrets of assets are registered.

## Which Areas Would Be Affected?
Broker Extension

## Why Is the Feature Desired?
Necessary for restarting a connector

## Solution Proposal and Work Breakdown
- [ ] Update Code
- [ ] Update documentation
- [ ] Update Process PUML
- [ ] ...

**Comment by tmberthold** [comment]
The broker automatically deactivates the assets in the event of a connector shutdown and is not explicitly initiated by the connector. So as soon as a connector reports that it is no longer accessible, its offers are deactivated at the Broker by the Broker and not by the Connector. Now it would actually be up to the Broker to reactivate the deactivated offers in case a connector should be reachable again, instead of sending the data again by the Connector.

_No guarantee, as another infrastructure component as the metadata broker is involved._
