### ISSUE TITLE
Adjust code-check pipeline to work with gradle

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-extensions#436]
See action [here](https://github.com/sovity/edc-extensions/blob/8dea5939a8ba874ce77720ea5894397ad08d43e3/.github/workflows/code_analysis.yml#L12)

**Comment by richardtreier** [comment]
As we have other mono repositories I would suggest that we don't keep syncing these "generic" pipelines.

Checkstyle, for example, is integrated into the gradle projects anyways. Other pipelines might need to be adjusted in monorepos anyways, as they won't otherwise catch a build.gradle.kts in the root directory.

**Comment by richardtreier** [comment]
We are moving closer and closer to have per-repository good CI, I believe I can close this issue in favor of us cleaning up automation per-repository step by step
