### ISSUE TITLE
Implement fix for Connector-Restricted-Usage Policy not working since EDC CE v5.0.0

### ISSUE THREAD

**Issue by tmberthold** [sovity/edc-extensions#727]
⚠️ **Bug Fix Delivery Required for MDS by Wednesday 14.02** ⚠️

# Bug Report

## Description

The [**Connector-Restricted-Usage Policy**](https://github.com/sovity/edc-extensions/tree/main/extensions/policy-referring-connector) is no longer working since EDC0 migration (EDC CE v5.0.0).

**Problem log**:
```
edc-extensions-edc2-1          | 2024-01-17 12:55:36 StateMachineManager [consumer-contract-negotiation] error caught 
edc-extensions-edc2-1          | java.lang.NullPointerException: Cannot invoke "org.eclipse.edc.spi.agent.ParticipantAgent.getClaims()" because the return value of "org.eclipse.edc.policy.engine.spi.PolicyContext.getParticipantAgent()" is null
edc-extensions-edc2-1          |        at de.sovity.edc.extension.policy.functions.AbstractReferringConnectorValidation.evaluate(AbstractReferringConnectorValidation.java:72)
[...]
edc-extensions-edc2-1          |        at org.eclipse.edc.protocol.dsp.dispatcher.DspHttpRemoteMessageDispatcherImpl.dispatch(DspHttpRemoteMessageDispatcherImpl.java:109)
[...]
```

**Short version**:
This has been a problem since migrating from core-edc MS8 to core-edc v0.2.1. Since then, the policy has not worked in any of our EDC CE versions (from EDC CE v5.0.0, regardless of whether dev or mds). With core-edc v0.1.2 breaking changes were introduced on how a core-edc's _PolicyContext_ can be built by the class-constructor, which no longer requires a _ParticipantAgent_. The core-edc class _DspHttpRemoteMessageDispatcher_ makes use of this possibility and builds a _PolicyContext_ without a _ParticipantAgent_, whereupon our Connector-Restricted-Usage Policy _AbstractReferringConnectorValidation_ subsequently throws the null pointer when invoking _policyContext.getParticipantAgent.getClaims()_.

**Technical derivation of the problem**:
Our class: nullpointer because _policyContext.getParticipantAgent()_ returns null when invoking _getClaims()_ on it at:
https://github.com/sovity/edc-extensions/blob/45d15241c59c1313de31fb179eabe3bc7991929a/extensions/policy-referring-connector/src/main/java/de/sovity/edc/extension/policy/functions/AbstractReferringConnectorValidation.java#L72

Changes to core-edc v0.1.2:
- The new default constructor _PolicyContextImpl()_ does not require a _ParticipantAgent_ and set's it to null when invoking the second class-constructor (L36). [LINK](https://github.com/eclipse-edc/Connector/commit/2e3ee8c424961f4f4703280f93adba1abb78dcb6#diff-0c2ac585810576289fdc58fe672ffa775671645c49c2786f8db098c7a88ea4f5)
- If the new _builder_ of the class is used, no _ParticipantAgent_ is set straight away through the new default constructor; the _ParticipantAgent_ must be set explicitly using the _additional_ method (L97).
- In core-edc's _DspHttpRemoteMessageDispatcherImpl_ there is such a _builder_ call that does not provide a _ParticipantAgent_ and then triggers the _policyEngine.evaluate_ after that (L91-95). [LINK](https://github.com/eclipse-edc/Connector/commit/2e3ee8c424961f4f4703280f93adba1abb78dcb6#diff-fe7f7803703fcab421a7dbaedd507e52d6ff92adf801b3c4c68c46e920627498)
- The logs above start from here. Due to the triggered _policyEngine.evaluate_, the non-existent _ParticipantAgent_ in the _PolicyContext_ is missing when evaluating the Connector-Restricted-Usage Policy, which then leads to the null pointer above by invoking _policyContext.getParticipantAgent().getClaims()_.

### Expected Behavior

The policy should work if it is selectable as a policy.

### Observed Behavior

See above, a NullPointer exception is thrown at evaluation time for the reasons mentioned above.

## Steps to Reproduce

Start any EDC CE variant, e.g. EDC CE DEV locally with the 2 standard EDC included in the docker-compose, add an asset, and select this policy within a contract definition as contract policy and negotiate the contract with a second connector.

## Context Information

**Outlook**:
As of core-edc v0.4.0 (not yet migrated to by us), the _PolicyContext_'s _getParticipantAgent_ method itself has additionally been removed.
https://github.com/eclipse-edc/Connector/commit/c9d6da4df3af14147ebdb7ea1bd688bd72924617#diff-0c2ac585810576289fdc58fe672ffa775671645c49c2786f8db098c7a88ea4f5

**Testing**:
Brainstorming between @tmberthold @jkbquabeck @richardtreier 
- We are considering to test the fix manually with the EDC CE dev-variant locally if there are no automated tests for this yet
   - deploying an EDC on sirius and testing it against the DAPS there could be a solution
   - Or testing it locally with a modified docker compose that connects to a DAPS

## Possible Implementation and Work Breakdown

```[tasklist]
- [ ] Understand the analysis and see if it is correct
- [ ] Check whether it can be fixed, as it has been a problem since EDC 0 migration or decide on removing the policy-extension at all.
- [ ] Provide a fix or remove the policy.
- [ ] Run manual test before delivery
```

**Comment by AbdullahMuk** [comment]
@efiege as aligned during today's daily, as your highest prio please implement the fix for this gap. Some important points:
- after you analyse the problem and plan a solution for it, please add your effort estimation (number of work days needed to implement fix) to the "Story Points" field 
- at the latest we want the fix to be implemented by Wednesday 14.02 so that we can ship out the fix in Raze release on Thursday 15.02 because we need to respect the M600 deadline for MDS 2.0. If your effort estimation exceeds this date, please contact me on Teams ASAP. 
- we agreed at daily today that we will test the topic manually because the E2E tests we want to implement during the scalability bootcamp will not be ready in time. Please contact @richardtreier to get the sample tests he has related to this topic. 

As needed, please contact me on Teams wherever I can support you more.

**Comment by tmberthold** [comment]
Because I saw the Issue was closed, this is still not working for me using the EDC CE DEV from the main-branch docker-compose for testing (using the main-branch-image).

Now there are no more NPEs, but I still don't see data offers with a connector-restricted policy if either used as access-policy or contract-policy in the consumer's catalog.

Provider Data Offers:
![image](https://github.com/sovity/edc-extensions/assets/75306992/16f8c597-c597-4929-8c1c-90a5cac9641d)

Consumer Catalog, only data-offers with just the always-true policy show up:
![image](https://github.com/sovity/edc-extensions/assets/75306992/91954e80-60b4-4e39-aa1d-0dbb5b8d4eb9)

Is there now somewhere a configuration property missing in the main docker-compose which needs to be set or how has this been tested? I was using the dsp-endpoint as well as the participant-id of the dashboard as restricted criterium.

**Comment by efiege** [comment]
This issue has been introduced when new `PolicyScopes` have been [added to the core-EDC](https://github.com/eclipse-edc/Connector/blob/c2de1fe3ebdb6c7a9fc0dd92c9fc89f955a3472f/data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/DspHttpCoreExtension.java#L60-L76).

These `PolicyScopes` are evaluated on incoming and outgoing dsp calls. For the incoming dsp calls this has not been an issue, because the counterParties identity can be fetched from the incoming token into a `ParticipantAgent`. On the other side there is no counterParty token available for outgoing requests.

To circumvent this issue, the registration of the policy has been changed. It is no longer registered for all scopes, but just for `contract.negotiation` and `catalog` scopes, such that this policy is evaluated for contract negotiation and retrieving the catalog, but not on a dsp-request level.
