### ISSUE TITLE
DataAddress can just be Updated using the v2 Asset Endpoint

### ISSUE THREAD

**Issue by efiege** [sovity/edc-extensions#902]
# Documentation Update Request

## Description
Assets might be updated by using the /v2 and /v3 endpoints of the management-API. However the dataAddress of the asset cannot be updated using the v3 api. This can just be done using the v2 asset endpoint.

**Comment by tmberthold** [comment]
That is not 100% correct: with the v3-api, the dataadress got embedded into the other asset-api, instead of having a seperate api for it: https://github.com/eclipse-edc/Connector/issues/3469
But there seems to be a bug in the current version, so the changes are not persisted: https://github.com/eclipse-edc/Connector/issues/3469

**Comment by SebastianOpriel** [comment]
@efiege please correct me when I am wrong: I understood that there is a known bug that prevents updating via this endpoint.

**Comment by tmberthold** [comment]
That's right, we've also just completely overhauled our postman collection, which uses the v2 APIs in exactly tat place. The v3 is buggy in exactly that place, which was also recognized as a bug in the core-edc and has since been fixed. Will work after the next core-edc migration also with v3. https://github.com/sovity/edc-extensions/blob/main/docs/api/postman_collection.json
